### ISSUE TITLE
Conduit does not work for Fragments

### ISSUE THREAD

**Issue by treelzebub** [Levelmoney/conduit#9]
The standard, non-loader implementation of Conduit does not support Fragments.

Reproduce:
1. Define a `com.levelmoney.conduit.Conduit` in a Fragment
2. Add, commit Fragment to Activity.
3. Call `load` in pretty much any lifecycle method, and it throws thusly:

```
Attempt to invoke virtual method 'void com.levelmoney.conduit.logic.ConduitRetainFragment.load(android.os.Bundle)' on a null object reference
com.levelmoney.conduit.Conduit.load(Conduit.java:80)
```

**Comment by treelzebub** [comment]
https://gist.github.com/treelzebub/40c2343da60f9f863b8b74efaea408eb

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.levelmoney.conduit.logic.ConduitRetainFragment.load(android.os.Bundle)' on a null object reference
    at com.levelmoney.conduit.Conduit.load(Conduit.java:80)
    at com.levelmoney.mobile.dev.TestFragment.onResume(TestActivity.kt:35)
    at android.support.v4.app.Fragment.performResume(Fragment.java:2238)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
    at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
    at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by treelzebub** [comment]
I have always intended to fix my open issues. I am just le-lazy :D

**Comment by treelzebub** [comment]
Okay, a couple things here:
1. We must make sure it's clearly documented that Conduit users must call `super.onViewCreated`, which they probably aren't accustomed to doing.
2. Conduit cannot be used by a Fragment with no UI, which is intuitive, but worth documenting.

Closing as not-a-bug.
